apiVersion: v1
kind: pod
metadata:
  creationTimestamp: null
  labels:
    run: bee
  name: bee
spec:
  containers:
  - image: nginx
    name: bee
  tolerations:
  - effect: Noschedule
    key: spray
    operator: In
    value: mortein
