apiVersion: v1
kind: ReplicationController
metadta:
  name: myapp-rc
  labels:
      app: myapp
      type: front-end
spec:
  template:

  metadata:
   name: myapp-pod
   labels:
      app: myapp
      type: front-end
  spec:
    container:
    - name: nginx-container
      image: nginx
