apiVersion: v1
kind: pod
metadata:
  labels:
    name: webapp-pod
  namespace: default
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    imagePull{olicy: Always
    name: webapp
    envFrom:
    - secretRef:
        name: db-secret
